steps:
  # Pull previous image
  - name: gcr.io/cloud-builders/docker
    args:
      - '-c'
      - 'docker pull $_ARTIFACT_HOSTNAME/$PROJECT_ID/$_ARTIFACT_REPO/$_IMAGE_NAME:latest || exit 0'
    entrypoint: bash

  # Build image
  - name: gcr.io/cloud-builders/docker
    args:
      - '-c'
      - >
        cp yarn.lock packages/$_TARGET_PACKAGE

        cd packages/$_TARGET_PACKAGE

        echo "copy $_ENV_FILE to .env.local"

        cp $_ENV_FILE .env.local

        docker build -t \

        $_ARTIFACT_HOSTNAME/$PROJECT_ID/$_ARTIFACT_REPO/$_IMAGE_NAME:${BRANCH_NAME}_${SHORT_SHA} \

        -t $_ARTIFACT_HOSTNAME/$PROJECT_ID/$_ARTIFACT_REPO/$_IMAGE_NAME:latest \

        --cache-from $_ARTIFACT_HOSTNAME/$PROJECT_ID/$_ARTIFACT_REPO/$_IMAGE_NAME:latest .
    entrypoint: bash

  # Push container image to registry
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_ARTIFACT_HOSTNAME/$PROJECT_ID/$_ARTIFACT_REPO/$_IMAGE_NAME:${BRANCH_NAME}_${SHORT_SHA}'


  # Deploy container image to Cloud Runs
  - name: gcr.io/cloud-builders/gcloud
    id: Deploy Image
    entrypoint: 'bash'
    args:
      - '-c'
      - |

        # read cloud run service names from substitution variable
        IFS=',' read -r -a cloud_runs <<< "$_CLOUD_RUN_SERVICE_NAMES"

        for cr in "${cloud_runs[@]}"
        do

        # deploy cloud run service iteratively
        gcloud run deploy "$cr" --image $_ARTIFACT_HOSTNAME/$PROJECT_ID/$_ARTIFACT_REPO/$_IMAGE_NAME:${BRANCH_NAME}_${SHORT_SHA} --region asia-east1

        done

  # Push container image to registry to update the latest one
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_ARTIFACT_HOSTNAME/$PROJECT_ID/$_ARTIFACT_REPO/$_IMAGE_NAME:latest'

timeout: 2400s

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _ARTIFACT_HOSTNAME: 'asia-east1-docker.pkg.dev' # default value
  _ARTIFACT_REPO: 'storytelling-docker-repo' # default value
  _TARGET_PACKAGE: '' # default value
  _IMAGE_NAME: '' # default value
  _CLOUD_RUN_SERVICE_NAMES: '' # default value
  _ENV_FILE: '' # default value
